version: "3.1"
services:
  pg:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "11111111"
      POSTGRES_DB: "rest_dev"
    ports:
      - "5432:5432"
