services:
  pg:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_USER: username
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres://username:pgpassword@pg:5432/mydatabase
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_USER: username
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres://username:pgpassword@pg:5432/mydatabase
      HOSTNAME: 0.0.0.0
      PORT: 8000
    links:
      - pg
    ports:
      - 8000:8000
    depends_on:
      - pg
    volumes:
      - ./:/app
    command: npm run module3
